[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.106.0" #请根据自己的 Hugo 版本进行修改
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo"

[context.split1.environment]
HUGO_VERSION = "0.106.0" #请根据自己的 Hugo 版本进行修改
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo"

[context.deploy-preview.environment]
HUGO_VERSION = "0.106.0" #请根据自己的 Hugo 版本进行修改

[context.branch-deploy]
command = "hugo"

[context.branch-deploy.environment]
HUGO_VERSION = "0.106.0" #请根据自己的 Hugo 版本进行修改

[context.next.environment]
HUGO_ENABLEGITINFO = "true"