# .github/workflows/douban.yml
name: douban
on: 
  schedule:
  - cron: "0 0,0,12,23 * * *"
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark static sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: wangyunzi
        type: movie
        format: csv
        dir: ./static/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: wangyunzi
        type: book
        format: csv
        dir: ./static/douban
        
    - name: music
      uses: lizheming/doumark-action@master
      with:
        id: wangyunzi
        type: music
        format: csv
        dir: ./static/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban static'
        add: './static/douban'